import { createElement } from "@lwc/engine-dom";
import ApprovalManagementForm from "c/approvalManagementForm";

describe("c-approval-management-form", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  const mockProjectCreatedInfo = {
    projectTitle: "Title Test",
    milestones: "1",
    tasks: "1"
  };

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-approval-management-form", {
      is: ApprovalManagementForm
    });

    element.projectCreatedInfo = mockProjectCreatedInfo;

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
